### ISSUE TITLE
Corner and contours cut off in the graph

### ISSUE THREAD

**Issue by mipodi** [epsalt/daylight#1]
Hi! What an excellent and inspiring project! I have tried to build upon this (mainly changing colours and other design choices). I have run into a problem that I first thought that I introduced myself but then I looked closer at your daylight graph and you have it too. 

Here is the top right corner of the graph zoomed in. Night ends before it should and also the other contours ends earlier than the y axis where they should hit the axis. 
![Screenshot 2023-08-25 at 14 22 16](https://github.com/epsalt/daylight/assets/43996895/a8c06b13-b5dc-4712-96e4-03c36c3852e6)

I get it in all my four corners but my visualization is much larger. It's also more visible when you remove the axis line.
![screencapture-127-0-0-1-5503-2023-08-18-12_11_59](https://github.com/epsalt/daylight/assets/43996895/e7e80160-2245-4bcb-84fa-be1e247c8325)

The D3 observable community suggested this could be a rounding issue, I have tried to mitigate this by forcing number of decimals when the graph width and height is calculated but it does not change anything.

I think it is a bit strange that it does, the data looks correct so why would it project this like so? 

Do you have any idea or suggestion what to do?

**Comment by mipodi** [comment]
I found now that I could "correct" it by removing one pixel of the width, as well as making the width and height divisible by resolution 60 and also remove all translations of the axes that I made.

**Comment by epsalt** [comment]
Glad you figured something out! Sounds like I have an off-by-one error in the width somewhere. Best of luck with your project.
